In [1]:
import pyrebase

ModuleNotFoundError: No module named 'pyrebase'

In [464]:
# from firebase import firebase
# firebase = firebase.FirebaseApplication("https://doctor-corona-a2b66-default-rtdb.firebaseio.com/",None)
# result = firebase.get('', '')

firebaseConfig = {
    "apiKey": "AIzaSyAlIvLFRo0wnq0llnzukfj9pQxAIM88yX0",
    "authDomain": "doctorcorona.firebaseapp.com",
    "databaseURL": "https://doctor-corona-a2b66-default-rtdb.firebaseio.com",
    "projectId": "doctor-corona-a2b66",
    "storageBucket": "doctor-corona-a2b66.appspot.com",
    "messagingSenderId":"517940316925",
    "appId":"1:517940316925:android:e34d3af1445e4115bd8c94"
    #measurementId:
}

firebase = pyrebase.initialize_app(firebaseConfig)

In [465]:
db = firebase.database()
database = db.get().val()
database
df = pd.DataFrame(database, columns=database.keys())
df = df.transpose()

In [466]:
Disease_AA = 2
Disease_BB = 3
Disease_CC = 4

In [467]:
df

,AGwGzWtGAqYr4bgPzcO8TKJrvjo2,MkqvZvIEeZU7FOu4CmRzXwqyam32,QqhFswknz7OWsd6vaV2jk4H0un83,RyRtOFZSmKeCuhuSjGJbUHMEXku1,ZSCdIUCh4MUZsgzQiCDVe0SPsP33,czWatN0VdbYEwCphpaVbLCWijem2,szpAfKkcurhAjA95OzejjFqy5dh1,x2dGpS5RWwXdEyg6X5ExV2EcVF32,yuoIqkBpTnNaiqKti2hX91P6f4B3,Age,Disease_A,Disease_B,Disease_C,Gender,Last,Name,Total,Vaccinated
Doctors,"{'docID': 'P003', 'email': 'champi@google.com'...","{'docID': 'P004', 'email': 'dydyd@fhf.xgf', 'n...","{'docID': 'P003', 'email': 'mypher99@gmail.com...","{'docID': 'P005', 'email': 'hfggchgh@xgc.ghv',...","{'docID': 'P004', 'email': 'kingo@fgood.com', ...","{'docID': 'P006', 'email': 'xhchg@gjh.gjh', 'n...","{'docID': 'P005', 'email': 'hi@iamhoeh.fyfy', ...","{'docID': 'P007', 'email': 'chhh@vhh.cv', 'nam...","{'docID': 'P002', 'email': 'manavkillseveryone...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,1,1,0,M,Almal,Shubh,0,1
P002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72,1,0,1,F,Reddy,Apoorva,0,1
P003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49,1,0,0,F,Singh,Khushi,0,0
P004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60,1,1,1,M,Mukherjee,Arko,0,0
P005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66,0,1,1,M,Singh,Rishabh,0,0
P006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66,0,0,1,M,xyz,Manav,0,0

In [ ]:
# def mergedicts(dict1, dict2):
#     for k in set(dict1.keys()).union(dict2.keys()):
#         if k in dict1 and k in dict2:
#             if isinstance(dict1[k], dict) and isinstance(dict2[k], dict):
#                 yield (k, dict(mergedicts(dict1[k], dict2[k])))
#             else:
#                 # If one of the values is not a dict, you can't continue merging it.
#                 # Value from second dict overrides one in first and we move on.
#                 yield (k, dict2[k])
#                 # Alternatively, replace this with exception raiser to alert you of value conflicts
#         elif k in dict1:
#             yield (k, dict1[k])
#         else:
#             yield (k, dict2[k])

In [ ]:
# def add_data(actual,new):
#     a = actual.to_dict()
#     b = new.to_dict()
#     p = dict(mergedicts(a,b))
#     p = pd.DataFrame.from_dict(p)
#     p.to_json(r'one.json')

#     return

In [468]:
dict_ = {'P_id':[],'Age':[],'Disease_A':[],'Disease_B':[],'Disease_C':[],'Gender':[],'Last':[],'Name':[],'Total':[],'Vaccinated':[]}

In [469]:
#Function for appending values in the dictionary!!
def set_key(dictionary, key, value):
    if key not in dictionary:
         dictionary[key] = value
    elif type(dictionary[key]) == list:
        dictionary[key].append(value)
    else:
        dictionary[key] = [dictionary[key], value]

#function for adding data into dataframe 
def add_data1(data=df,dict_=dict_):
   # dict_ = {'P_id':[],'Age':[],'Disease_A':[],'Disease_B':[],'Disease_C':[],'Gender':[],'Last':[],'Name':[],'Vaccinated':[]}
    P_id = input("Enter Patient ID : ")
    Name = input("Enter Patient Name : ")
    Last = input("Enter Patient Last Name : ")
    Age = int(input("Enter Patient Age : "))
    Gender = input("Enter Patient Gender : ")
    Disease_A = int(input("Enter 1 if 'Yes',0 otherwise : "))
    Disease_B = int(input("Enter 1 if 'Yes',0 otherwise : "))
    Disease_C = int(input("Enter 1 if 'Yes',0 otherwise : "))
    Vaccinated = int(input("Enter 1 if 'Yes',0 otherwise :"))
    Total = 0
    values = [P_id,Age,Disease_A,Disease_B,Disease_C,Gender,Last,Name,Total,Vaccinated]
    for i,j in zip(dict_.keys(),values):
        set_key(dict_,i,j)
    d = pd.DataFrame(dict_)
    
    return d

#Function for calculating the Total
def calculate_Total(data):
    for i in range(ds.shape[0]):
        x = 0
        for j in range(ds.shape[1]):
            if(ds.iloc[i,j]== 1):
                if(ds.columns[j] == 'Disease_A'):
                    x = x + Disease_AA
                elif(ds.columns[j] == 'Disease_B'):
                    x = x + Disease_BB
                elif(ds.columns[j] == 'Disease_C'):
                    x = x + Disease_CC
        ds['Total'][i] = x

In [470]:
number_of_patients = int(input("Enter number of patients :"))
for i in range(number_of_patients):
    ds = add_data1()

Enter number of patients :2
Enter Patient ID : P007
Enter Patient Name : asd
Enter Patient Last Name : awe
Enter Patient Age : 78
Enter Patient Gender : M
Enter 1 if 'Yes',0 otherwise : 1
Enter 1 if 'Yes',0 otherwise : 0
Enter 1 if 'Yes',0 otherwise : 0
Enter 1 if 'Yes',0 otherwise :0
Enter Patient ID : P008
Enter Patient Name : awe
Enter Patient Last Name : asd
Enter Patient Age : 89
Enter Patient Gender : F
Enter 1 if 'Yes',0 otherwise : 1
Enter 1 if 'Yes',0 otherwise : 1
Enter 1 if 'Yes',0 otherwise : 1
Enter 1 if 'Yes',0 otherwise :0

In [471]:
ds

,P_id,Age,Disease_A,Disease_B,Disease_C,Gender,Last,Name,Total,Vaccinated
0,P007,78,1,0,0,M,awe,asd,0,0
1,P008,89,1,1,1,F,asd,awe,0,0

In [479]:
df = pd.concat([df,ds.set_index("P_id")])
df

,AGwGzWtGAqYr4bgPzcO8TKJrvjo2,MkqvZvIEeZU7FOu4CmRzXwqyam32,QqhFswknz7OWsd6vaV2jk4H0un83,RyRtOFZSmKeCuhuSjGJbUHMEXku1,ZSCdIUCh4MUZsgzQiCDVe0SPsP33,czWatN0VdbYEwCphpaVbLCWijem2,szpAfKkcurhAjA95OzejjFqy5dh1,x2dGpS5RWwXdEyg6X5ExV2EcVF32,yuoIqkBpTnNaiqKti2hX91P6f4B3,Age,Disease_A,Disease_B,Disease_C,Gender,Last,Name,Total,Vaccinated
Doctors,"{'docID': 'P003', 'email': 'champi@google.com'...","{'docID': 'P004', 'email': 'dydyd@fhf.xgf', 'n...","{'docID': 'P003', 'email': 'mypher99@gmail.com...","{'docID': 'P005', 'email': 'hfggchgh@xgc.ghv',...","{'docID': 'P004', 'email': 'kingo@fgood.com', ...","{'docID': 'P006', 'email': 'xhchg@gjh.gjh', 'n...","{'docID': 'P005', 'email': 'hi@iamhoeh.fyfy', ...","{'docID': 'P007', 'email': 'chhh@vhh.cv', 'nam...","{'docID': 'P002', 'email': 'manavkillseveryone...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,1,1,0,M,Almal,Shubh,0,1
P002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72,1,0,1,F,Reddy,Apoorva,0,1
P003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49,1,0,0,F,Singh,Khushi,0,0
P004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60,1,1,1,M,Mukherjee,Arko,0,0
P005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66,0,1,1,M,Singh,Rishabh,0,0
P006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66,0,0,1,M,xyz,Manav,0,0
P007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,1,0,0,M,awe,asd,0,0
P008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89,1,1,1,F,asd,awe,0,0
P007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,1,0,0,M,awe,asd,0,0
P008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89,1,1,1,F,asd,awe,0,0
P007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78,1,0,0,M,awe,asd,0,0
P008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89,1,1,1,F,asd,awe,0,0

In [482]:
db.update(ds.set_index("P_id").T.to_dict())

{'P007': {'Age': 78,
  'Disease_A': 1,
  'Disease_B': 0,
  'Disease_C': 0,
  'Gender': 'M',
  'Last': 'awe',
  'Name': 'asd',
  'Total': 0,
  'Vaccinated': 0},
 'P008': {'Age': 89,
  'Disease_A': 1,
  'Disease_B': 1,
  'Disease_C': 1,
  'Gender': 'F',
  'Last': 'asd',
  'Name': 'awe',
  'Total': 0,
  'Vaccinated': 0}}

In [460]:
df

,AGwGzWtGAqYr4bgPzcO8TKJrvjo2,MkqvZvIEeZU7FOu4CmRzXwqyam32,QqhFswknz7OWsd6vaV2jk4H0un83,RyRtOFZSmKeCuhuSjGJbUHMEXku1,ZSCdIUCh4MUZsgzQiCDVe0SPsP33,czWatN0VdbYEwCphpaVbLCWijem2,szpAfKkcurhAjA95OzejjFqy5dh1,x2dGpS5RWwXdEyg6X5ExV2EcVF32,yuoIqkBpTnNaiqKti2hX91P6f4B3,Age,Disease_A,Disease_B,Disease_C,Gender,Last,Name,Total,Vaccinated
Doctors,"{'docID': 'P003', 'email': 'champi@google.com'...","{'docID': 'P004', 'email': 'dydyd@fhf.xgf', 'n...","{'docID': 'P003', 'email': 'mypher99@gmail.com...","{'docID': 'P005', 'email': 'hfggchgh@xgc.ghv',...","{'docID': 'P004', 'email': 'kingo@fgood.com', ...","{'docID': 'P006', 'email': 'xhchg@gjh.gjh', 'n...","{'docID': 'P005', 'email': 'hi@iamhoeh.fyfy', ...","{'docID': 'P007', 'email': 'chhh@vhh.cv', 'nam...","{'docID': 'P002', 'email': 'manavkillseveryone...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,1,1,0,M,Almal,Shubh,0,1
P002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72,1,0,1,F,Reddy,Apoorva,0,1
P003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49,1,0,0,F,Singh,Khushi,0,0
P004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60,1,1,1,M,Mukherjee,Arko,0,0
P005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66,0,1,1,M,Singh,Rishabh,0,0
P006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66,0,0,1,M,xyz,Manav,0,0

,P_id,Age,Disease_A,Disease_B,Disease_C,Gender,Last,Name,Total,Vaccinated
0,P007,76,1,1,1,M,awe,asd,0,0

<ipython-input-404-a9639011b11d>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds['Total'][i] = x

,P_id,Age,Disease_A,Disease_B,Disease_C,Gender,Last,Name,Total,Vaccinated
0,P007,76,1,1,1,M,awe,asd,9,0

<ipython-input-380-9eb38ee720a3>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds['Total'][i] = x